In [3]:
import numpy as py
import pandas as pd

In [4]:


df = pd.read_csv("Reviews.csv")
print(df)

            Id   ProductId          UserId                      ProfileName  \
0            1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian
1            2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa
2            3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"
3            4  B000UA0QIQ  A395BORC6FGVXV                             Karl
4            5  B006K2ZZ7K  A1UQRSCLF8GW1T    Michael D. Bigham "M. Wassir"
...        ...         ...             ...                              ...
568449  568450  B001EO7N10  A28KG5XORO54AY                 Lettie D. Carter
568450  568451  B003S1WTCU  A3I8AFVPEE8KI5                        R. Sawyer
568451  568452  B004I613EE  A121AA1GQV751Z                    pksd "pk_007"
568452  568453  B004I613EE   A3IBEVCTXKNOH          Kathy A. Welch "katwel"
568453  568454  B001LR2CU2  A3LGQPJCZVL9UC                         srfell17

        HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                          1                       1      5  1303862400
1                          0                       0      1  1346976000
2                          1                       1      4  1219017600
3                          3                       3      2  1307923200
4                          0                       0      5  1350777600
...                      ...                     ...    ...         ...
568449                     0                       0      5  1299628800
568450                     0                       0      2  1331251200
568451                     2                       2      5  1329782400
568452                     1                       1      5  1331596800
568453                     0                       0      5  1338422400

                                   Summary  \
0                    Good Quality Dog Food
1                        Not as Advertised
2                    "Delight" says it all
3                           Cough Medicine
4                              Great taffy
...                                    ...
568449                 Will not do without
568450                        disappointed
568451            Perfect for our maltipoo
568452  Favorite Training and reward treat
568453                         Great Honey

                                                     Text
0       I have bought several of the Vitality canned d...
1       Product arrived labeled as Jumbo Salted Peanut...
2       This is a confection that has been around a fe...
3       If you are looking for the secret ingredient i...
4       Great taffy at a great price.  There was a wid...
...                                                   ...
568449  Great for sesame chicken..this is a good if no...
568450  I'm disappointed with the flavor. The chocolat...
568451  These stars are small, so you can give 10-15 o...
568452  These are the BEST treats for training and rew...
568453  I am very satisfied ,product is as advertised,...

[568454 rows x 10 columns]

In [5]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 568454 entries, 0 to 568453
Data columns (total 10 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Id                      568454 non-null  int64
 1   ProductId               568454 non-null  object
 2   UserId                  568454 non-null  object
 3   ProfileName             568428 non-null  object
 4   HelpfulnessNumerator    568454 non-null  int64
 5   HelpfulnessDenominator  568454 non-null  int64
 6   Score                   568454 non-null  int64
 7   Time                    568454 non-null  int64
 8   Summary                 568427 non-null  object
 9   Text                    568454 non-null  object
dtypes: int64(5), object(5)
memory usage: 43.4+ MB
None

In [6]:
print(df.isnull().sum())

Id                         0
ProductId                  0
UserId                     0
ProfileName               26
HelpfulnessNumerator       0
HelpfulnessDenominator     0
Score                      0
Time                       0
Summary                   27
Text                       0
dtype: int64

In [7]:
df['ProfileName']=df['ProfileName'].fillna(df['ProfileName'].mode()[0])
df['Summary']=df['Summary'].fillna(df['Summary'].mode()[0])

In [8]:
print(df.isnull().sum())

Id                        0
ProductId                 0
UserId                    0
ProfileName               0
HelpfulnessNumerator      0
HelpfulnessDenominator    0
Score                     0
Time                      0
Summary                   0
Text                      0
dtype: int64

#Outlier chek

In [9]:
cols = ['HelpfulnessNumerator', 'HelpfulnessDenominator']

for col in cols:
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    IQR = q3 - q1
    lower = q1 -1.5*IQR 
    upper = q3 + 1.5*IQR
    
    outlier = df[(df[col] < lower) | (df[col] > upper)]
    print(col, "Outliers:", len(outlier))

HelpfulnessNumerator Outliers: 37002
HelpfulnessDenominator Outliers: 52643

In [10]:
df = df[(df[col] >= lower) & (df[col] <= upper)]

In [11]:
print("duplicate value",df.duplicated().sum())

duplicate value 0

# Data types

In [12]:
df['Time'] = pd.to_datetime(df['Time'], unit='s')

In [13]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 515811 entries, 0 to 568453
Data columns (total 10 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Id                      515811 non-null  int64
 1   ProductId               515811 non-null  object
 2   UserId                  515811 non-null  object
 3   ProfileName             515811 non-null  object
 4   HelpfulnessNumerator    515811 non-null  int64
 5   HelpfulnessDenominator  515811 non-null  int64
 6   Score                   515811 non-null  int64
 7   Time                    515811 non-null  datetime64[ns]
 8   Summary                 515811 non-null  object
 9   Text                    515811 non-null  object
dtypes: datetime64[ns](1), int64(4), object(5)
memory usage: 43.3+ MB
None

#Matrics Banana

In [28]:
top_users = df['UserId'].value_counts().head(5000).index

top_products = df['ProductId'].value_counts().head(5000).index

In [29]:
df_filtered = df[
    df['UserId'].isin(top_users) &
    df['ProductId'].isin(top_products)
]

In [30]:
matrix = df_filtered.pivot_table(
    index='UserId',
    columns='ProductId',
    values='Score'
).fillna(0)

In [26]:
print(matrix)

ProductId       7310172001  7310172101  B00004CI84  B00004CXX9  B00004RAMY  \
UserId
A100WO06OQR8BQ         0.0         0.0         0.0         0.0         0.0
A1051DBTLWP5A2         0.0         0.0         0.0         0.0         0.0
A1080SE9X3ECK0         0.0         0.0         0.0         0.0         0.0
A10AFVU66A79Y1         0.0         0.0         0.0         0.0         0.0
A10G136JEISLVR         0.0         0.0         0.0         0.0         0.0
...                    ...         ...         ...         ...         ...
AYWUHB7N8XGZQ          0.0         0.0         0.0         0.0         0.0
AZ4QFFUT8QVTA          0.0         0.0         0.0         0.0         0.0
AZ4T61QUJHA9E          0.0         0.0         0.0         0.0         0.0
AZ5X928CQPRJN          0.0         0.0         0.0         0.0         0.0
AZV26LP92E6WU          0.0         0.0         0.0         0.0         0.0

ProductId       B00004RYGX  B00014DXCC  B0001ES9F8  B0001ES9FI  B00020HHAO  \
UserId
A100WO06OQR8BQ         0.0         0.0         0.0         0.0         0.0
A1051DBTLWP5A2         0.0         0.0         0.0         0.0         0.0
A1080SE9X3ECK0         0.0         0.0         0.0         0.0         0.0
A10AFVU66A79Y1         0.0         0.0         0.0         0.0         0.0
A10G136JEISLVR         0.0         4.0         0.0         0.0         4.0
...                    ...         ...         ...         ...         ...
AYWUHB7N8XGZQ          0.0         0.0         0.0         0.0         0.0
AZ4QFFUT8QVTA          0.0         5.0         0.0         0.0         5.0
AZ4T61QUJHA9E          0.0         0.0         5.0         0.0         0.0
AZ5X928CQPRJN          0.0         0.0         0.0         0.0         0.0
AZV26LP92E6WU          0.0         0.0         0.0         0.0         0.0

ProductId       ...  B008O3G2K2  B008RWUHA6  B008RWUKXK  B008YA1NWC  \
UserId          ...
A100WO06OQR8BQ  ...         0.0         0.0         0.0         0.0
A1051DBTLWP5A2  ...         0.0         0.0         0.0         0.0
A1080SE9X3ECK0  ...         0.0         0.0         0.0         0.0
A10AFVU66A79Y1  ...         0.0         0.0         0.0         0.0
A10G136JEISLVR  ...         0.0         0.0         0.0         0.0
...             ...         ...         ...         ...         ...
AYWUHB7N8XGZQ   ...         0.0         0.0         0.0         0.0
AZ4QFFUT8QVTA   ...         0.0         0.0         0.0         0.0
AZ4T61QUJHA9E   ...         0.0         0.0         0.0         0.0
AZ5X928CQPRJN   ...         0.0         0.0         0.0         0.0
AZV26LP92E6WU   ...         0.0         0.0         0.0         0.0

ProductId       B008ZRKZSM  B0090X8IPM  B00954NY46  B00954NYVY  B009E7YC54  \
UserId
A100WO06OQR8BQ         0.0         3.0         0.0         0.0         0.0
A1051DBTLWP5A2         0.0         0.0         0.0         0.0         0.0
A1080SE9X3ECK0         0.0         0.0         0.0         0.0         0.0
A10AFVU66A79Y1         0.0         0.0         0.0         0.0         0.0
A10G136JEISLVR         0.0         0.0         0.0         0.0         0.0
...                    ...         ...         ...         ...         ...
AYWUHB7N8XGZQ          0.0         3.0         0.0         0.0         0.0
AZ4QFFUT8QVTA          0.0         0.0         0.0         0.0         0.0
AZ4T61QUJHA9E          0.0         0.0         0.0         0.0         0.0
AZ5X928CQPRJN          0.0         0.0         0.0         0.0         0.0
AZV26LP92E6WU          0.0         0.0         0.0         0.0         0.0

ProductId       B009RB4GO4
UserId
A100WO06OQR8BQ         0.0
A1051DBTLWP5A2         0.0
A1080SE9X3ECK0         0.0
A10AFVU66A79Y1         0.0
A10G136JEISLVR         0.0
...                    ...
AYWUHB7N8XGZQ          0.0
AZ4QFFUT8QVTA          0.0
AZ4T61QUJHA9E          0.0
AZ5X928CQPRJN          0.0
AZV26LP92E6WU          0.0

[848 rows x 488 columns]

In [32]:
matrix.fillna(0)

ProductId,7310172001,7310172101,B00002N8SM,B00004CI84,B00004CXX9,B00004RAMX,B00004RAMY,B00004RBDU,B00004RYGX,B00004S1C6,...,B009AFJ548,B009B87SAC,B009E7YC54,B009GHI5Q4,B009HXB2JO,B009IQLAQK,B009M2LPHO,B009M2LRTA,B009M2LUEW,B009RB4GO4
UserId,,,,,,,,,,,,,,,,,,,,,
A100WO06OQR8BQ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A101P2KHWCU0G6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
A102LH0KD8SYHX,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A102UXGLDF76G1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A103U3KR4L2ZXT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AZU8GQQW6HESP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AZV26LP92E6WU,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AZWRZZAMX90VT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AZXKAH2DE6C8A,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AZYMD9P9F9UZ6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [33]:
matrix[matrix > 0]

ProductId,7310172001,7310172101,B00002N8SM,B00004CI84,B00004CXX9,B00004RAMX,B00004RAMY,B00004RBDU,B00004RYGX,B00004S1C6,...,B009AFJ548,B009B87SAC,B009E7YC54,B009GHI5Q4,B009HXB2JO,B009IQLAQK,B009M2LPHO,B009M2LRTA,B009M2LUEW,B009RB4GO4
UserId,,,,,,,,,,,,,,,,,,,,,
A100WO06OQR8BQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A101P2KHWCU0G6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
A102LH0KD8SYHX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A102UXGLDF76G1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A103U3KR4L2ZXT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AZU8GQQW6HESP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AZV26LP92E6WU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AZWRZZAMX90VT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AZXKAH2DE6C8A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AZYMD9P9F9UZ6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN